[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# Redirects and headers
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Identity settings
[dev]
  command = "npm run dev"

# Netlify CMS proxy redirect
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Enable Netlify Identity
[[redirects]]
  from = "/.well-known/openid-configuration"
  to = "https://api.netlify.com/.well-known/openid-configuration"
  status = 200
  force = true

# Git Gateway - lebih spesifik
[[redirects]]
  from = "/.netlify/git"
  to = "https://api.netlify.com/api/v1/repos"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/git/*"
  to = "https://api.netlify.com/api/v1/repos/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/identity/*"
  to = "https://api.netlify.com/api/v1/identity/:splat"
  status = 200
  force = true 